#!/bin/bash

export PLATFORM=$(uname)
export PIP_CMD="python3 -m pip"
export ANCHOR_POINT=$(pwd)
export GIT_HOST="git@HOST"

to_anchor() {
  cd $ANCHOR_POINT
}

install_dependencies() {
  $PIP_CMD install --upgrade pip
  $PIP_CMD install --upgrade -r requirements.txt
  [ -d src ] && (cd src && for i in */requirements.txt; do $PIP_CMD install -r $i; done)
}

create_venv() {
  python3 -m venv ./venv/${PLATFORM} # assume python version is at least 3.4
}

[ ! -e ./venv/${PLATFORM}/bin/activate ] && create_venv && . ./venv/${PLATFORM}/bin/activate && install_dependencies
[ ! -e ./venv/${PLATFORM}/bin/activate ] || . ./venv/${PLATFORM}/bin/activate
